In [1]:
import keras.preprocessing 

/Applications/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [2]:
from keras.datasets import cifar10

In [3]:
!pip install np_utils

In [4]:
(x_train, y_train), (x_test, y_test) = cifar10.load_data()

In [5]:
from keras.utils import to_categorical

In [6]:
keras.__version__

'2.2.4'

In [7]:
y_train = to_categorical(y_train, num_classes=None)
y_test = to_categorical(y_test, num_classes=None)

In [8]:
y_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       ...,
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.]], dtype=float32)

In [9]:
y_test

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.]], dtype=float32)

In [10]:
datagen = ImageDataGenerator(
    featurewise_center=True,
    featurewise_std_normalization=True,
    rotation_range=20,
    width_shift_range=0.2,
    height_shift_range=0.2,
    horizontal_flip=True)

# compute quantities required for featurewise normalization
# (std, mean, and principal components if ZCA whitening is applied)
datagen.fit(x_train)

# fits the model on batches with real-time data augmentation:
model.fit_generator(datagen.flow(x_train, y_train, batch_size=32),
                    steps_per_epoch=len(x_train) / 32, epochs=epochs)

# here's a more "manual" example
for e in range(epochs):
    print('Epoch', e)
    batches = 0
    for x_batch, y_batch in datagen.flow(x_train, y_train, batch_size=32):
        model.fit(x_batch, y_batch)
        batches += 1
        if batches >= len(x_train) / 32:
            # we need to break the loop by hand because
            # the generator loops indefinitely
            break

NameError: name 'ImageDataGenerator' is not defined

In [11]:
# Using Pillow

In [1]:
import os
os.getcwd()

'/Users/pradmishra/Documents'

In [8]:
from PIL import Image, ImageFilter
#Read image
im = Image.open( 'IMG_20190131_180201__01.jpg' )
#Display image
im.show()

#Applying a filter to the image
im_sharp = im.filter( ImageFilter.SHARPEN )
#Saving the filtered image to a new file
im_sharp.save( 'image_sharpened.jpg', 'JPEG' )

#Splitting the image into its respective bands, i.e. Red, Green,
#and Blue for RGB
r,g,b = im_sharp.split()

#Viewing EXIF data embedded in image
exif_data = im._getexif()
exif_data

{256: 4608,
 257: 3456,
 34853: {0: b'\x02\x02\x00\x00',
  1: 'N',
  2: (12.0, 56.0, 35.1132),
  3: 'E',
  4: (77.0, 35.0, 46.8924),
  5: b'\x00',
  6: 832.7,
  7: (12.0, 32.0, 1.0),
  29: '2019:01:31'},
 34665: 172,
 271: 'OnePlus',
 272: 'ONEPLUS A6000',
 305: 'Picasa',
 274: 1,
 306: '2019:01:31 18:02:02',
 36864: b'0220',
 37377: 5.643,
 37378: 1.53,
 36867: '2019:01:31 18:02:02',
 36868: '2019:01:31 18:02:02',
 37380: 0.0,
 40961: 1,
 40962: 4608,
 37384: 0,
 37385: 16,
 37386: 4.25,
 40963: 3456,
 40965: 746,
 41989: 25,
 33434: 0.02,
 33437: 1.7,
 42016: '4b54de5d31273e130000000000000000',
 34850: 2,
 34855: 200,
 41987: 0}

In [5]:
im.getdata()

In [3]:
list(im.getdata())

[(0, 7, 0),
 (2, 9, 1),
 (2, 9, 1),
 (8, 15, 7),
 (8, 15, 7),
 (3, 10, 2),
 (6, 13, 5),
 (7, 14, 6),
 (7, 14, 6),
 (5, 13, 2),
 (0, 8, 0),
 (0, 7, 0),
 (11, 19, 8),
 (15, 23, 12),
 (13, 21, 10),
 (28, 36, 25),
 (0, 9, 0),
 (6, 17, 1),
 (18, 29, 13),
 (14, 25, 9),
 (35, 46, 30),
 (22, 33, 17),
 (21, 32, 16),
 (18, 29, 13),
 (25, 36, 20),
 (30, 41, 25),
 (23, 34, 18),
 (38, 49, 33),
 (34, 45, 29),
 (23, 34, 18),
 (22, 33, 17),
 (27, 38, 22),
 (21, 32, 16),
 (18, 29, 13),
 (18, 29, 13),
 (17, 28, 12),
 (14, 25, 9),
 (18, 29, 13),
 (26, 37, 21),
 (28, 39, 23),
 (25, 36, 20),
 (21, 32, 16),
 (20, 31, 15),
 (16, 27, 11),
 (9, 20, 4),
 (11, 22, 6),
 (20, 31, 15),
 (27, 38, 22),
 (19, 25, 11),
 (3, 9, 0),
 (1, 7, 0),
 (16, 24, 9),
 (7, 15, 0),
 (0, 5, 0),
 (10, 21, 5),
 (17, 30, 13),
 (13, 26, 9),
 (19, 33, 16),
 (16, 30, 13),
 (9, 26, 8),
 (0, 17, 0),
 (17, 34, 16),
 (21, 38, 20),
 (16, 35, 16),
 (26, 39, 21),
 (38, 51, 33),
 (34, 47, 29),
 (24, 37, 19),
 (18, 32, 15),
 (7, 21, 4),
 (2, 16, 0

In [37]:
# https://lodev.org/cgtutor/color.html

In [39]:
import numpy as np
np.array(list(im.getdata()))

array([[ 0,  7,  0],
       [ 2,  9,  1],
       [ 2,  9,  1],
       ...,
       [82, 93, 53],
       [68, 79, 39],
       [78, 89, 49]])

In [16]:
4608*3456*3

47775744

In [41]:
data = np.array(list(im.getdata()))

In [42]:
data.shape

(15925248, 3)

In [44]:
f_data = data.flatten()

In [45]:
f_data.shape

(47775744,)

In [46]:
15925248*3

47775744